* 詞彙表
1. 議題: 社會議題
2. 組織: 有法人實體 / 有代表性成員
3. 社群: 無法人實體 / 有核心成員 / 有固定 gathering 的 event / 有共同做某件事
4. 技術社群: 以討論技術為主軸的社群, e.x Pyhug
5. 設計社群: 以討論設計為主軸的社群
6. 公民科技社群: 以科技解決社會問題的社群, e.x. g0v
7. 議題社群: 以討論社會議題為主軸的社群, e.x 山域政策監督聯盟
8. 愛好者社群:愛好某個產品的社群, e.x. Mozilla, Emacs
9. 事件(Event):	有時序的資料，可以是新聞、公文、社群網路討論串、公聽會等等。
10. 標籤(Tag): 資料集的屬性。
11. 分類(Category): 互斥的資料集 。
12. 動機(Motivation): 行為背後的價值判斷。 (需要有另一人挖掘 insights)
13. 立場(Position): 對特定議題的觀點。
14. 問題(Problem): 通常由行政官僚，政策分析師等提出對策。
15. 議題(Issue): "政客，媒體，政治顧問透過分析、界定、區格與標籤等手段將問題轉化成對社會真實的爭辯。 p.123, 公關政治學, ""問題是必須加以解決的，而議題卻只是政治人物用來混淆選民以追求本身仕途的工具"" ~ Dirty Politics, Kathleen H. Jamieson"
16. 議題設定: 指大眾傳播媒介通過報導內容的方向及數量，對一個議題進行強調。
17. 議題框架效應: 一個問題用兩種說法，兩種說法在邏輯意義上其實是相似的，然而卻導致了不同的決策判斷。
18. 期望結果: 群眾判斷要不要對特定議題繼續爭辯的準則。
19. 信任網路(Trust Network): http://en.wikipedia.org/wiki/Wikipedia:Trust_network
20. Filter Bubble: A result state in which a website algorithm selectively guesses what information a user would like to see based on information about the user (such as location, past click behavior and search history) and, as a result, users become separated from information that disagrees with their viewpoints, effectively isolating them in their own cultural or ideological bubbles.
21: 機會之窗 (policy window of opportunity；John Kingdon，1984 ): 問題、政策備選方案，以及政治條件同時連結，有較高機會建立政府議程推動政策。
