#+TITLE: 網路社群參與機制設計與建議報告
#+AUTHOR: 陳信屹、簡韻真
#+EMAIL: ossug.hychen@gmail.com
#+DATE:
#+OPTIONS: H:2 num:t

* 目錄                                                                  :TOC:noexport:
- [[#前言][前言]]
- [[#正文][正文]]
  - [[#報告一摘要][報告一摘要]]
  - [[#報告二摘要][報告二摘要]]
- [[#產生文件][產生文件]]
- [[#授權][授權]]

* 前言
  隨著網路原生代族群漸漸成為國家中堅力量，利用數位工具或是社交媒體議論時政已為稀鬆平常之事，過去政府嘗試的網路政策或願景參與，多在政策制定或執行端末期，由科技社群協助提供執行上的意見參考，未能更廣泛的搜集科技社群或一般大眾意見，同時缺乏良好的機制有系統、大規模的萃取有用的意見進入政策規劃週期，以至於政策制定者常常忙著滅火，本分項計畫完整驗證一整套模式，也讓科技社群參與設計本模式與相關工具，建立未來科技政策審議之基礎建設。

本分項計畫的前身是 2013 年社群發起的 g0v 專案「鄉民關心您」，一個企圖處理蒐集，整理，串連，行動，追蹤的多中心化群眾參與社會議題的平台。
在 2017 年經由開放文化基金會獲科技會報補助，作為一個分項計畫，研究如何讓更多公眾的意見進入 2030 年科技願景及科技政策的討論中。為了達到由下往上的公共參與科技政策，讓網路原生代和科技社群可以設定議程、對議題和政策提出意見，作為一個開源專案，開發三樣東西：

1. 議題整理工具：在原始文件上標注意見，並用心智圖的方式整理，幫助釐清議題爭點。
2. 議題釐清小聚：讓網路原生代、科技社群在平日晚上小聚（meetup）就可以討論科技政策的方法。
3. 數位原民參與手冊：訪談科技社群成員與公務員，提供科技社群如何與政府互動的指南。

本分項計畫相信唯有公民和科技社群（或是任何網路社群）能夠自發討論去影響科技政策，才能達成由下而上的公民參與，與更好的科技政策。因此 不是要再架一個數位參與平台作為跟政府反映意見的管道，也不是再架一個線上跟政府提案的網站，也不是設計一套大型會議的線上參與機制，而是設計多中心化的討論方法和工具，降低社群討論科技政策的門檻。目標是政府補助案結束後，科技社群能夠像開發開源專案一樣，持續討論科技政策、分享有效的策略、維護開發議題整理工具。
* 正文
  本報告框架可分為「由上而下」以及「由下而上」兩個部分：
  1. 由上往下盤點網路社群關心議題操作建議 - 以資訊科技社群與科技政策為例。 全文見[[./report1/README.org][報告一]] 。
  2. 由下往上促進網路社群討論政策操作建議 - 以資訊科技社群與科技政策為例。 全文見[[./report2/README.org][報告二]]。
** 報告一摘要
   #+INCLUDE: ./report1/README.org::中文摘要 :only-contents t
** 報告二摘要
  #+INCLUDE: ./report2/README.org::中文摘要 :only-contents t
* 產生文件
  #+BEGIN_SRC shell
  make
  #+END_SRC
* 授權
  本研究完整的「Source」可從 https://github.com/SenseTW/ArrTMDReport 取得，內容除特別標註外，均採[[https://creativecommons.org/licenses/by-sa/4.0/deed.zh_TW][「姓名標示-相同方式分享 4.0 台灣 （CC BY-SA 4.0 TW]]」授權公眾使用。

  如有特別標註者依其說明授權。本研究附加檔案或為其他著作人所有，已力求詳細標註出處，請依原作聲明方式利用。
