* Profile
 1. 天下雜誌：用公民科技突圍中國封鎖　g0v共同發起人高嘉良：中國來跟台灣嗆民主？不會吧！ https://www.cw.com.tw/article/article.action?id=5085997, https://medium.com/@clkao/cw-interview-73848141ac5 .
 2. 光華雜誌：公民黑客力 g0v零時政府 https://www.taiwan-panorama.com/tw/Articles/Details?Guid=61281c3d-f79c-4db7-93d9-d18b29f90ba0&CatId=1
* 訪談逐字稿
- ael：主要是分成兩個部分是，我們現在就我們KPI要兩個嘛，一個是要做線上意見整理的工具，然後另外一個是要寫一本像社群協作手冊，所以現在手冊想要分兩個部分，一個部分是跟政府說你跟網路社群開會的時候要注意什麼東西，那我們現在過去這幾次訪談有一些東西像是網路沒有代表人，或是有人希望會議可以提供資料，或者是希望可以滾動式修正之類的。
- B：你說滾動式修正是什麼？
- ael：就是希望比如說開第一次會……
- （A中離）
-   ael：突然覺得我應該整理好……我來試試看那個Google語音輸入到底有多強大，嗯……沒關係我們都用正常講話。
-   KL：你要……你有需要什麼協助嘛？
-   ael：好像……算了，好像沒有很厲害。
-   KL：啊那個好像需要一點時間。
-   ael：不行，不行。
-   B：你用Apple的不行？
-   ael：Apple的……你連講話他也要跟你講句號他才會講句號。
-   B：沒有你就最後再編輯就好了。
-   ael：最後再編輯……可以用Apple的，Apple跟Google的差不多，但是Apple的好像沒有辦法持續一個小時，會斷掉，好沒有關係，你先講好了。我那天試過他大概過一段時間。
-   B：會爛掉？
-   ael：會爛掉，他沒有辦法撐到一個小時，他過一段時間會爛掉。好，所以我想要那個……想要問你有沒有什麼給一個一邊是給政府的建議，然後另外一邊是給社群他想要影響政策的建議。
-   clkao：這是問題嘛？
-   ael：嗯……對。
-   KL：有什麼意見要傳遞進去之類的？
-   ael：對，我功課做不夠，我還沒有把那個整理出來，就是你現在去那個時候比如說剛開始找你進去跟這些政府開會的時候，你覺得是什麼東西是開會、或者是你已經跟他們磨合兩三年了，什麼是……現在如果有一個新單位找你進去開會你希望他們事先指導的是？
-   clkao：這個是開什麼會，有很大不同啊，然後他到底是政策的什麼階段？
- ael：那我們如果現在把他
- clkao：你們有大概分類嘛？
- ael：那……政策階段的話，現在有一些、有一些是意見蒐集嘛，有一些是review，然後比如像你那個是決定要不要預算或者是要不要給那個，那如果我們先放在意見蒐集、意見蒐集這個層次的會議
- clkao：嗯……對，但是意見蒐集還是有不同的階段。
- ael：意見蒐集還是有不同的階段……
- clkao：就是他已經有想要幹嘛、然後來蒐集，還是他不知道要幹嘛？這會不大一樣。
- ael：那我們先假設他不知道他要幹嘛，例如像 Join 上次那個，那樣子已經有提案，你會覺得他是不知道要幹嘛還是……
- clkao：你說哪一個？
- ael：前兩個禮拜 JOIN 的那個會議。
- clkao：那個會議不是要 revise 他的辦法？對不對，所以他已經有方案了
- ael：他已經有方案了，是要針對這個方案去做討論跟 comment，OK。
- clkao：那這個就很明確，這個就是……
- ael：我們先從他已經有議程，比如說 Join這個他要revise。
- clkao：那如果是這樣那就是討論的標的很明確，那 outcome 可能是蠻明確的吧，就是大家都覺得很好，或是大家都覺得不大好，就有疑慮，或者是這個完全不行。
- ael：你說的大家是誰？
- clkao：就是今天假設是一個……反正就是一個線上的社群在討論，或者是任何去參加這個會議的，因為他的結果可以想像是幾種嘛。
- ael：對，你是說譬如說像政府說想要做這三個事情，然後我們可以針對這三點去提出意見。是這樣嗎？
- clkao：對對對，你現在講的是剛才那個case，對不對，所以他已經有……
- ael：他有revise，他有想要做三件事
- clkao：對啊對啊，那大家就針對這三件事去討論，或者是覺得別的方案比較好。
- ael：對。
- clkao：對不對，那所以是這個情況的話那其實算是單純，就是你儘早讓大家可以先自行討論，先匯集意見。
- ael：所以就比如說會議記錄可以先出來……不是會議記錄，會議 material。
- clkao：對啊，會議material。然後他本身的建議的背後的邏輯跟佐證的資料……
- ael：可是通常這些會議資料是只有那份 PDF 檔他會給你佐證的資料嗎？研究報告還是？
- clkao：有的會稍微講，那或者是有的是簡報檔。
- ael：簡報檔會先提供嗎？
- KL：那……參與會議的人他們，譬如說自己有知道相關的參考資料或是可能就是會議上面列出來，那在這種情況應該要怎麼辦？
- clkao：怎麼提供是不是？
- KL：對怎麼提供然後你要怎麼促進……
- ael：OK，如果是……我們先不講就是說要更廣泛參與的情境下好了，假設是一個委員會好了，那他本來就會邀請這些委員去嘛，所以那通常作法是號稱在一個禮拜前要提供資料，但最後通常是兩天到三天前，但是同時間你如果委員要發言，有想要投影出來或是要給其他的人的，會議的logistic通常會幫你處理。就是你先提案，你先把一些簡報或是什麼寄過去，那你發言的時候請他切過去講。所以這個是有可能的，所以如果你已經有一個很...... alternative的論點，那你有佐證資料像投影片之類的，通常就是還是可以做。
- KL：可是這個情況會發生的兩種狀況，一個是開會之前、一個是已經開會，就是開會之前你可能有相關資料就請召集的人寄給大家，那假設如果是你們在開始進入討論到相關的東西的時候，那這種時候又該如何……
- clkao：這種時候，你是說你已經知道有這個資料了嗎？還是你也不知道？
- KL：沒有是我們開始進入討論之後，然後可能討論到某個相關東西的時候，喔，就有相關的資料要再加進來。
- clkao：但是那個資料是已知還是未知？你如果現場提出來就現場討論，你如果沒辦法現場討論你就說這個……如果他嚴重到必須要再討論就是下一次討論，通常是這樣子。
- ael：所以比如說事前……可是因為會議記錄會兩三天前才到你的信箱，所以就……
- clkao：你是說會議資料？
- ael：會議資料。你也不會.......你會先寄給其他委員嗎？
- clkao：你說我要提供……
- ael：你要講什麼？你會先寄還是？
- clkao：不一定。
- ael：所以你有寄過？也沒有寄過？
- clkao：對啊。
- ael：所以你有寄過的話你會用什麼方法寄？
- clkao：通常只是文字的重點，就是我要講什麼這樣子。
- ael：那其他人會這樣做嗎？
- clkao：嗯……有些會，但不多。
- ael：不多，大家大部分都是到現場，再……
- clkao：因為大家其實開這種會大家都很忙，所以很多都是……我猜大部分人根本事前不會看資料，都是現場看。
- ael：就是現場看，所以現場都會用紙本印出來？
- clkao：對，雖然開會通常都會說不提供紙本資料，但是都會印出來，也不提供紙杯，但是會提供杯子。
- 10:18 
- ael：所以都會印出來。然後就是我這次去NCC（會議名稱）的時候會有一張簡報檔，就是簡報印成紙本。那會議紀錄節錄之後會再寄給所有人？
- clkao：對。
- ael：所以通常在開會之前，你會跟其他與會的人，交換他們意見？
- clkao：大部分的時候你其實不知道誰要去開會。
- ael：那會議通知上不會寫？
- clkao：呃……會議通知會有，但是正式會議通知也是兩三天前，除非他是一個固定的委員會你就知道誰會去。像開放資料的那個資訊，那個民間委員都是固定的，那大家就會交換意見。
- ael：所以還要看他是什麼性質？
- clkao：對啊你如果是一次性的委員審查或是意見諮詢，那其實你根本不知道他一開始邀誰，那直到正式的會議通知出現……
- ael：那……所以那我們現在假設，剛剛是假設不公開的狀況，就是不公開委員的狀況，我們之前收到的建議有包括說，要搞清楚這個專家的專業在哪，他的cover範圍是什麼，然後再找他進來審這個案子，或者是盡量在會議前提供會議資料，然後你覺得還有什麼方法在這種不公開的專家會議，就先說是一次性好了，不公開的一次性的審的東西的……政府會議中進行哪些事情，對你來說是有幫助的？
- clkao：呃……其實很多時候你是沒有足夠的 background，譬如說你有的時候審查，他可能要請你比較去年的績效，可是其實他不會給你去年績效或是去年的計畫，那所以你就要再去要資料，那可是你真的要看那麼多資料？其實沒有那麼多時間。那所以就是說有的時候你審查重點或是說你開會的……如果今天是審查的形式啦，審查的重點是什麼？其實應該要更細、就更明確，譬如說他有一些預算編列是不是合理的？這個不一定每個人都對這個有了解、了解怎麼編列，那是不是預算就是另外一種審，實質內容跟預算怎麼編跟最後deliver出來的東西，每個人看的地方可能不大一樣，那怎麼更細緻的去做，或者是說你……我想想看……或是說基本的guideline，因為他今天譬如說問你你這個案子適不適合給他錢，可是你給錢的標準是什麼？其實並不很明確。
- ael：那像通常審查會議會多久？如果是給錢的案子。
- clkao：不一定，就是有的是書審，你提意見他們再回覆，啊有的是一輪，有的是兩輪之後才開始會議，可能看規模大小會不一樣。
- ael：那其實我們的重點應該是，這個會議是可以公開的、然後你會去蒐集意見的，像這樣的會議通常是哪一些會議？
- clkao：這個有一些諮詢性的，就是政策已經有一個初步的諮詢性的，譬如說中選會要做罷免的電子聯署系統，那他們有一個草案，那我因為那個時候是中選會的諮詢委員，他就說要開會，我就問他說這個可不可以先更廣泛的蒐集意見。那他們是同意的，同意那我就是把它貼出來社群，讓大家來給意見。但是這個對社群譬如說我去參加這個會，但是如果今天這個意見真的非常多的話，其實要花很多力氣去整理，所以這就是我們這個play book，社群的那個手冊可以幫到忙的地方，就是現在當然兩三個意見大家彙整得出來，像有人說這個有人說那個，我們就一次把它報出來，這個很簡單，那如果說是意見非常的多非常的分歧非常的多元，那怎麼去統整起來……
- 16:05 
- ael：這有出現過嗎？
- clkao：呃……沒有。但是這個我覺得啦，因為像是你說罷免那個它可能時間稍微長一點，大概一個禮拜，這已經算很長了，但是你要讓社群討論可能還需要更多的時間然後……怎麼cheer這個討論，最後怎麼收斂意見。
- ael：那所以你說通常會有兩三個人的意見？比如說你貼中選會罷免，那貼出來有其他人給你意見嗎？
- clkao：有啊你可以先看那個……
- ael：現在應該還在？
- clkao：對現在應該還在，Google hackpad社群就好了。
- ael：為什麼它叫我log in？search要log in嗎？
- clkao：要，search要log in。
- （聽不太清楚，不太重要）
- ael：所以你的方法是你會開一個hackpad，然後請大家comment？
- clkao：對啊，這個公職人員罷免案電子聯署諮詢意見的……這個其實有兩三個人給意見，Danny、kiang跟祖儀嘛，祖儀他其實有出席這個會，因為他是少數的罷免案的領銜人，所以他線上有參與討論，現場也有去。
- ael：那你有把你的那個、你自己有在上面寫你的想法嗎？
- clkao：有啊，在這裡啊，對啊。
- ael：然後所以Danny跟kiang就有放下去……所以是……你是丟slack跟facebook裡面嗎？你會只丟 slack還是會丟facebook？
- clkao：我都……通常都丟吧，就是後勤中心跟那個……
- ael：加上會議簡報。那你會把之後這個東西帶回社群嗎？
- clkao：你是說討論階段？如果是現場做就會先 note。
- ael：那 note是？比如說這樣子，祖儀隨手note。所以那開會的結果你會再貼回社群來嗎？
- clkao：呃……開會其實這種的話他也不會再告訴你有什麼結果啊。
- ael：譬如說……其他人在那個會議裡面說什麼，就不是你和祖儀的那個。
- clkao：這種的會議紀錄好像通常沒那麼細，那其他人說什麼……我沒有印象欸。對我印象中是沒有收到會議紀錄的。
- ael：就是會後會寄會議紀錄這件事情會常常執行嗎還是就是？
- clkao：我想一下。對啊這個我沒有收到紀錄。
- 20:09 
- clkao：對啊，像這種諮詢會議他好像通常不做，就我們不是一個常設的委員會，不是一個諮詢委員會，而是他特定議題的諮詢，那通常他也不見得會做一個公開的紀錄。
- ael：所以如果今天在你的hackpad上comment，我想要知道最後發生什麼事然後去問你。
- clkao：沒有我也不知道最後發生什麼事啊。
- ael：你知道會議中發生什麼事啊。
- clkao：我知道會議中發生什麼事啊。
- ael：但是你也不知道最後就是……發生什麼事，但如果我想要知道會議中發生什麼事就要問你。
- clkao：對啊，但是我也不見得記得全部啦，因為我那天好像也先走。
- ael：所以通常這種可以公開諮詢的，然後是一次性的，就是有沒有……
- clkao：也不一定啊像是……
- ael：開放資料諮詢委員會。
- clkao：開放資料諮詢委員會他有一些提案那，其實也是可以公開諮詢。
- ael：你有丟到社群嗎？
- clkao：好像有，之前有一個什麼修改的，對。但是呃……就是他那個諮詢小組他其實是可以做出決議的嘛，可是這個諮詢小組他不是一個小組，他就是對於這個議題來問他意見，那沒有什麼決不決議，那他們最後參考這些意見再作出調整，這也是他們自己會做的。那要促進更多人參與，當然是要讓他這個結果可以……可能在一個iteration吧，至少在他這個新的辦法出現到他實際執行之前可能還有再討論的空間。那因為像我現在我也不知道他最後設計的系統是怎樣，因為大家有蠻多不同的意見，但法規規定他要做嘛，但要怎麼做、做成什麼樣子，就是他們行政機關可以決定的。
- ael：所以其實像這次Join那個後來Peggy有去整理三場的討論記錄。
- clkao：為什麼有三場？不同議題還是一樣議題？
- ael：好像是一樣議題，我不太確定到底……我現在正在要Peggy做的，就有人跟我說Peggy做記錄統整，我正在要想要看到底發生什麼……
- clkao：但是本來就有公開的記錄嗎？
- ael：沒有，那個是Peggy在第三次還是第四次會議的時候報告的內容。然後我問了誠夏去Join那場，他說他現在也還沒收到會議紀錄所以……所以他也不知道後續發生什麼事。
- clkao：對啊這種不見得會有會議記錄。
- ael：公開諮詢的。
- clkao：諮詢會不見得會有會議記錄，就是你是特定小組的這種就會有，因為你就是這個小組的成員啊，那……
- ael：特定小組通常會有會議記錄喔？
- clkao：就是你要確認你的發言嘛，會做成會議記錄。
- ael：可是……我以為不特定諮詢應該要會有會議記錄。
- clkao：應該要有啦，他們內部會有但是有沒有正式的就不曉得，這個是研商會議。
- ael：對，但是後來……你這是單頁的，就這個但不是那場就是後面還有一場，像那誠夏就不知道，那whisky知道。
- clkao：那那場是什麼？
- ael：我還沒有確定那場到底是什麼，只是聽……
- clkao：所以是不一樣的？
- ael：對，就不是這場。
- clkao：那應該是這個的最後他們內部的討論吧。
- ael：可能吧，然後那次Peggy 有去做手動整理這些討論的這件事，但一般會議是不會的。所以現在目前有的狀態是，遇到諮詢的你會問他們能不能公開，然後如果可以公開你會把它附上pdf檔，或可能是會議簡報，貼個hackpad，請大家comment，但是通常只有兩三個人會來comment，因為時間也很短通常只有兩三天。
- clkao：對，而且因為關心特定議題的人本來就有限。
- 25:04 
- ael：而且……呃你覺得原本的資料有辦法讓一般之前沒關心議題的人，看到這些資料就有辦法加入討論嘛？
- clkao：看議題啊，中選會那個當然他有一些技術背景啦，但是技術的人就是OK啊。
- ael：對，一定都會有一些……
- clkao：對啊，如果像那個法規類的要求嘛，然後要做什麼樣的東西……
- ael：那這個是你開會錢，所以，就是剛剛hackpad連的就是連這份，你把它變成google簡報，讓大家可以comment，是不是第一次？還是……
- clkao：有嗎？
- ael：所以把它變成……那你有記得除了中選會這個之外還有其他你有丟出來的？
- clkao：不知道欸，都要看hackpad。
- ael：你通常會叫什麼？會議嗎？
- （討論感冒）
- ael：經貿國是會議你有參加嗎？
- clkao：沒有。
- ael：所以你沒有參加那種……本來就是比較，設計來做公民參與的會議？
- clkao：那個什麼智慧網路新台灣那個，我有參加過。那個是要共同去出一個白皮書嘛，那個我有去參加。
- ael：你是以什麼身分參加？
- clkao：我是……我也不知道欸。
- ael：我是說是，民間、路人……
- clkao：民間啊。
- ael：OK。（我的hackpad開得特別慢。）
- clkao：其實我覺得剛才我們講的一些具體的建議除了提供資料之外，其實應該是可以推薦出席的人。
- ael：就是不是直接就邀你。
- clkao：就是你願不願意出席，你覺得誰是這個領域適合邀請的人。
- ael：因為常常你覺得你不是專家……
- clkao：什麼？
- ael：常常你不一定是最專家的人。
- clkao：對啊我不一定啊。
- ael：好，還有……他們那時候說他來是個人不是代表網路，沒有一個人可以代表網路，那個時候剛跟政府開會的時候需要強調的事情。所以你在開會的時候你會去提說這是社群的意見嘛？
- clkao：對啊對啊，如果像是那個中選會……
- ael：你可能就會說有A觀點B觀點，然後誰說什麼什麼，然後就是把他列出來這樣。
- clkao：對啊
- 29:59 
- ael：那如果今天反過來今天是一個他以前從來沒有被找去政府開過外部專家諮詢會議的人，他第一次要被找進……譬如說你今天推薦他，但是他從來沒有跟政府開過會，你覺得他應該要注意什麼？一些比較具體的，像是搞清楚你這個機關的業務職掌範圍，錢是怎麼來，與會者或主席誰要做決定，這可能是一個你去之前最好要準備，或者是……你其實可以在會議前跟承辦人要更多的會議資料，就他可能只有給你那一份，可是他不知道你其實想要看某一份資料，你可以寫信去問他說有沒有那份資料。
- clkao：其他的……
- ael：更具體的情境好了……假設最近可能要開一個類似AI教育人才的諮詢會議，然後這是一個一次性廣納大家意見的會議，那有人今天比方是我好了，我可以提出提案，有什麼建議可以給我？
- clkao：就是他已經要去……
- ael：他已經受邀了，但他從來沒有跟政府開過會。
- clkao：就是呃……他如果已經有準備發言要用的簡報可以先給承辦人，那搞清楚這些context這個當然是必須的啦，因為你要知道這個會的outcome是什麼，但是這其實應該是自己的期待管理啦，因為有的會是你當然會讓大家覺得是這樣，但是後來其實是長官……覺得不是這樣，你這個跟你去開會的人也沒有太大的關係，除非你是說你們做的所有決定如果沒有用你就不去。
- ael：所以你覺得外部專家在這樣的會裡面通常是扮演什麼樣的角色？就是讓社群的聲音可以進去，然後有把話講出來、講清楚，然後其實後續溝通或是有沒有落實政策就超過了。
- clkao：對，因為你怎麼追蹤跟……就是這個effort很大，這個已經超過去諮詢的，那你如果本身自己很care、你想去follow，那這個社群怎麼organize起來、怎麼去follow這件事情，這可能是這個社群手冊裡面可以提到的部分。
- ael：你有organize大家follow，或某一次開會的……
- clkao：這個你問柏鋒比較好，他都一直在follow晶片身分證的問題，但是你，就是說，因為這個個人要做有點難，你要花很多時間，你要去關心他最近的發展。而且特定議題可能有點冷門，所以怎麼樣是，也許法人提供一些機制去追蹤。
- ael：你是說，比如NGO有在追蹤。
- clkao：對，因為大部分議題其實有守備範圍，某些議題就是某些人會去追嘛，啊但是像這些數位的東西，數位人權之類的東西，其實有點真空，就是台權會的一些會關心，但是他們的議題還蠻多的，所以這一部份其實也是他們的主力。
- ael：那……你在這種如果遇到意見跟你很不合的人，你會做出什麼反應？
- clkao：你說會議上？會議上意見不合什麼反應……
- ael：就是他也是民間單位，但是你覺得他講的東西就是bull shit。
- clkao：那我就說我不同意他的看法啊。
- ael：你會有機會講到第二輪嗎？……
- clkao：通常會。會議通常不會說大家講完就結束啦，就大家都還是蠻尊重譬如說你如果還想發言的話……
- ael：可是這樣會拖很久嗎？他們有限制大家發言時間嗎？
- 35:58 
- clkao：網路社群怎麼去organize，怎麼去follow……
- ael：那基本上你在……你在g0v 採取的 approach是有這樣的社群空間讓大家可以討論，然後大家知道可以把這樣的議題丟到這邊，會獲得回應。我的觀察是你不太主動去organize特別的議題討論，除非你有被找進去當委員。
- clkao：對啊。
- ael：那你覺得……
- （ 36:36 到38:09 不太清楚，break）
- ael：OK，那剛剛是說你對沒有去參加過政府會議的人有什麼建議，但目前沒有想到太多建議，就是開會然後去提案，把你想講的東西講一講。
- clkao：對啊，或者是看他是什麼身分，他如果想要有自己的社群做討論，那就是用類似的方法。
- ael：類似的方法是？他可以丟到他的社群去做討論，所以這個社群可以是一個通訊群祖，也可以是一個臉書社團、mailing list，你有在mailing list討論過這個嗎？
- clkao：沒有。
- ael：你沒有在mailing list討論過會議的事情。但是政府發邀請的時候會發到那個mailing list、那個 group裡面。
- clkao：你說 g0v-talk嗎？
- ael：g0v-talk ，但是發邀請的時候通常不會到g0v-talk ，所以發言演講才會到 g0v-talk ，沒有我只是好奇。
- clkao：問號？
- ael：我是問號……
- clkao：有時候會，對，就是個案處理啊，但不會在那邊討論，因為那可能是一個random政策，跟talk群組沒有關係。
- ael：OK，了解。所以……好，但我覺得社群有一個mailing list做為聯絡窗口是個好的approach，就是你可以 make sure這個會議邀請或這個資訊社群內部是只有一個人看到，不會被block在那邊，由那個人決定要或不要或者是……
- clkao：對，所以我想社群的窗口……就等於是他提供一個窗口。
- 40:14 
- ael：對，那如果是經常性開會，例如開放資料諮詢小組，你有當過？那這樣子的會議，你覺得政府應該在經常性的會議應該要做到哪些事情？
- clkao：我覺得應該是說，如果是這種民間參與的小組的話，應該要讓他的功能比這個會議再更多一點，比如說那種半年開一次會的，你下一次追蹤就是半年後了……就是大家能拖的時間一樣。
- ael：現在是變成，法定是一年兩次嘛對不對，所以在那之前這些開放資料小組更頻繁地開會？
- clkao：本來是各部會是四次……
- ael：對，一季一次……一季一次夠嗎？
- clkao：就會議討論應該算是夠，就是盤點他的資料，看新的需求這些東西。
- ael：那你們各個委員之間會分工嗎？
- clkao：沒有，沒有分工，就是出席會議。
- ael：出席會議，然後……這些人也是政府機關的人找進來的，然後他們就是出席會議。
- clkao：大部分……應該是這樣子。
- ael：所以是政府機關去決定他要不同專長的人進來這裡。你之前在哪個單位，這是公開資訊嗎？
- clkao：都是公開的，中選會的、行政院的。
- ael：那個開放資料小組有幾個人？
- clkao：呃……通常都是十來個人，那民間要派三分之一。
- ael：所以一樣是會先放會議資料，然後……但這個會不會更早一點？因為這是常態性編組。
- clkao：不會。但我想可能每個部會做法不一樣。
- ael：但你目前如果還是要兩三天前……
- clkao：大部分。
- ael：那會議通知，就是什麼時候要開會，是多久以前？
- clkao：會議會蠻早先敲定，大約三四個禮拜前會敲。
- ael：那material是兩三天前到，然後所以有十幾個人，三分之一是民間委員，你們就去開會，然後去看他們報告的事情。你們可以agenda setting嗎？例如第一次會議說我下次會議想要看到什麼。
- clkao：可以，因為小組可以做成決議，就是說下次邀請誰，那當然這個要主席同意。
- ael：但是比如說這種想做成決議的東西，你事前也不會跟其他委員討論，就是會議上大家開始。
- clkao：對啊，因為你事前還不一定知道你想要做這件事。
- ael：所以這樣會議開會時間三四個小時還是……
- clkao：沒有啦，沒有開三四個小時，頂多兩個小時，很少超過兩個半小時。
- ael：所以就會這樣把會……做成決議，那如果下一次看到沒有……就是你們說請他們去做什麼或去研究什麼，那三個月後沒有看到的話？
- clkao：通常不會啦，大家還是稍微會有做一點。
- ael：但是在這種小組編制的case裡面，你會去跟社群說這個會議嗎？
- clkao：有時間的話會。
- ael：但這樣其實大部分的時間是你沒有時間去丟會議的material，或者是解釋這個會議發生什麼事情？
- clkao：對啊，所以其實一個可以做的就是default open，那政府也許開這個會，那他material都是公開的對不對，那一種方式就是說任何人都可以提意見，但是你的意見不一定會被討論，但是你們可以讓委員看你的意見是值得被排進來討論的嗎，所以這個做法也變成不是說每個人自己去蒐集意見，而是說你就是，反正你某一個方式去公開的爭取意見，那有一些意見他當然比較popular，你可能就主動，或者是本來就是這個小組的委員他可以選定……
- ael：所以像開放資料資訊小組這個東西的東西是可以被往外討論的？
- clkao：理論上是可以啦。
- ael：但你沒有想試過？
- 45:52 
- clkao：應該有試過，但是我不記得了。
- ael：那再問一個問題就是，你去要求default open，或會議open的話你覺得有包括哪幾個方法……像是meeting或是諮詢會議……
- clkao：再講一次
- ael：就是你說default open嘛，你覺得哪些 criteria 或是哪些東西是做到可以算是default open？
- clkao：你說做到什麼才算是default open？
- ael：或者是我今天政府說我也想要default open，可是我不知道default open可以怎麼做？
- clkao：嗯……其實想像上就是說把general public當作會來參與會議的人，那執行上你怎麼去做，那當然material是可以公開的，那蒐集意見的管道是大家都可以提的，那當然就會有bandwidth 的問題。大家都可以提就不一定所有東西都可以被討論，那還是要有一個機制去決定什麼是必須被討論的論點或者是……那再來就是，反過來講的話，參與這個議題討論的人，他們通常不公開。
- ael：什麼意思？
- clkao：如果今天是政府他要open，而我提供意見的人不想要公開，那怎麼辦？
- ael：比如說我外部專家不想公開還是……general public？
- clkao：比如說我今天提一個意見，可是我不想讓大家知道那是我提的。
- ael：可是通常政府會說有人覺得不能公開就不會公開。
- clkao：對啊但我的意思就是說在這種情境下我們要怎麼處理？
- ael：你是說，容許……可是他都已經是去開會的人了耶，他還是想要匿名？
- clkao：有些會這樣，但我的意思就是說，這個就是實際上可能會發生的，所以當他如果想要提供意見的話就必須要處理到這樣的問題，對不對？機制上……
- ael：那實務上有什麼建議嘛？
- clkao：不知道啊，因為現在沒有人這樣做啊，沒有default open。
- ael：喔，因為上次我跟NCC開會是，我問可不可以公開，但結果facebook跟google代表說他們不可以，因為他們如果要公開一定要經過總部的PR同意，所以他們不能公開對外發言，所以他們說這個會議不能公開。政府就有幫我問，但他們就說不行。
- clkao：對啊，但是這個合理嗎？他不公開，那主辦會議的單位能不能做總整然後公開？反正這個就是機制上必須要……
- ael：然後接下來就有人說那這跟公聽會有什麼差別，就如果這是一個專家會議，然後你要對所有人公開，那這個跟公聽會的差別是什麼？
- clkao：當然就是有些專家你可能本來不會邀到，就來的人不一定是 random的人 ，他當然很多是random 的人 ，那所以就是怎麼樣設計一個機制是讓重要的意見還是能夠在會議裡面被討論。
- ael：我現在想的事情是其實真正關心而且可以討論的人是少數，只是他不一定有被找到會議裡，但這個人數可能少到我覺得很難超過十個人會對那次的東西發表很多大量的comment，至少你目前也還沒遇到過對不對？。所以如果……這就不是手冊內容，就是sense.tw 怎麼刺激大家願意……
- clkao：對啊，那你就必須要降低門檻，或是讓這些人可以願意出現。
- ael：所以像 JOIN 那個我有看到你貼那篇文，可是我……
- clkao：我貼什麼？
- ael：就是你有說誠夏要去，要給意見，但是我那時候就會覺得我對JOIN沒什麼想法，我也其實沒有很真的用過它，我看過那份文件了，可是你要叫我提出什麼comment好像很困難，因為我並沒有……即便那時候因為工作的關係開始稍微認識JOIN，但我就還是覺得沒有辦法對那份文件提出comment，所以我就沒有comment。那對於科技社群想要做倡議你有建議嗎？
- clkao：有什麼具體的例子嗎？
- ael：例如你們去發布手冊啊，然後你做 g0v.news就是……等於是跟媒體去倡議，在我看來g0v.news比較像是一個媒體去倡議相關的東西，然後更新相關的資訊，或者是舉辦黑客松實體活動，去維繫大家的感情。
- clkao：那個不是倡議啊……
- ael：喔那不是倡議，所以你覺得g0v.news不算倡議的一部份？
- clkao：沒有，倡議就是支持一個政策然後你就是要這樣做……
- ael：嗯嗯，所以，那像開放政府，這算你的倡議嗎？你有在做這件事？
- clkao：可是他、就是說，你不一定要具體的政策才能夠叫做倡議吧，就是你要能夠很容易檢驗這個事情有沒有發生，那你才會有一個倡議的主題跟你有沒有倡議成功。
- ael：我之前不覺得有這麼明確，因為很多人會說我倡議數位人權，可是數位人權也是一個你很難去檢驗有沒有成功的東西，因為他會step by step，那當然這中間會再拆成campaign ，例如我要網路中立性，就是不可以……這樣的話就是一個 campaign ，然後另外一個就是假設政府機關要蒐集人民的資料必須要人民的同意，這也是一個campaign ，可是長遠來說他可以二十年都倡議數位人權，就是比較沒有end point啦。我以為是 campaign 才比較有一個 endpoint，就是這個政策有沒有過。所以像開放政府這件事也是很難有end point……
- clkao：對啊，應該是說你那是議題跟精神啦，那你如果假設說你的倡議是一個議題而不是特定政策，那可能一種是你被動性地去……相關的政策出現的時候你去follow，那一種是你要很主動的說，那這個議題就是要做ABC三件事情，那這個當然就需要更大的能量才有辦法做，等於你要提出一個完整的政策。
- ael：所以其實你現在都還沒有做到提出完整的政策這件事，還是你有提出完整政策或完整議題是你希望去推的？
- clkao：你說我嗎？
- ael：對，個人。
- clkao：有一些東西啦，例如說法人改革的東西，但是這個都還沒有更廣泛公開的討論，那當然我有一些想法就是在董事會提嘛……
- ael：你是說在資策會的董事會提？
- clkao：對，那你說關心的議題，開放政府或……open data這些東西，你說我提一個完整的政策但沒有……那應該算是比較有在follow政府在做哪些事情，那可能某些時候有場合或機會對他們計畫的一些建議這樣。
- ael：所以……比較像是你剛好在一個會被諮詢的角色跟位置，所以當有人來諮詢你開放資料或者是公民參與相關主題的話就會針對這些題目還是審查計畫也好，或是給建議也好，就是會給出建議這樣。所以我如果現在具體要你說你現在在倡議什麼，或者是你希望政策往哪個方向走，你講得出來嗎？
- clkao：你說哪一個部分？
- ael：比如說開放資料。
- clkao：應該是說，我不會覺得……呃，它必須要有一個政策roadmap……那這是不是一個meta政策？
- ael：所以跟政府開會的時候，政府會給政策roadmap嗎？
- clkao：不會，通常政府沒有什麼政策roadmap，他只有就是一個bla大型計劃，那依據blablabla行政院某某決議要做某件事情，那其實政府自己的roadmap是很破碎的。
- ael：所以你在會裡面看的是它的roadmap？你在會議裡面要求的是他有roadmap嗎？
- clkao：沒有沒有，你現在在問我我有沒有自己的政策想法，這當然沒有辦法在會議裡面，就是這也是會有，但是會議通常都是比較specific的問題。
- ael：所以通常都是在解決這件問題上面？
- clkao：嗯哼。
- ael：那……這個好像有點岔開話題，就是你會開始進入這些諮詢角色是因為三一八的關係嗎？還是其實更早？
- clkao：應該更早吧。就是那個時候去，第一次去行政院就是hychen也一起去啊，那個時候還沒有三一八。
- ael：可以說那時候去幹嘛嗎？
- clkao：那時候就是……應該是蔡玉玲他想要一些網路政策之類的，就蒐集大家的想法跟意見。
- ael：了解，所以那時候開始……好，那手冊這邊我能問的都問完了，但我想問你……你有要問嗎？（對 KL）
- KL：為什麼大家都這麼愛用hackpad？就我其實不太懂……
- ael：問這個引入者……
- KL：就是為什麼g0v 大家這麼愛用 hackpad，就是他到底有哪些功能上的好處會讓你就是……
- clkao：你說跟什麼比起來？
- KL：跟Google docs、dropbox paper、evernote……
- clkao：主要是以社群來講嘛，就是authership 是一個很重要的東西，就是你可以直接在文件上做誰和誰的討論，那這個在google docs，很麻煩，就是你一定要用一個comment討論，那我其實文件可以inline去做討論，那這個當然也不見得只有好處，那但是共同編輯一份文件裡面看到哪一部份是誰寫的話，它其實對社群參與者來講有credit。
- 
- 1:00:33 
- ael：在 g0v 裡面有credit很重要，或是在開源社群裡面有credit也很重要。
- clkao：那這是一個重點，當時其實沒有其他工具做這個做的比較好，只有Etherpad，但比較不友善。那它對就是不熟悉這些工具的人算比較好上手。
- ael：像HackMD也方便，可是他一定要打 Markdown，加一些語法，你一旦會了之後覺得沒有很難，可是那不是一般人使用的習慣。
- KL：比如說大小寫或是上色之類的。
- ael：不是不是，加井字號變標題，加link也要用中括號括起來，小括號再去加 link，就不是一般人的使用邏輯。我們在 Hackpad 關的那個時候還有列了一串，包括work space，就g0v你可以，就算別人沒有主動跟你說他在做這個，但你去 g0v的hackpad，你就可以知道其他人在討論什麼事情，你不需要主動。
- clkao：對，那是另外一個就是workspace的一個概念，那大家可以follow，就是淺度參與follow其他的討論。
- ael：而且是我想要看的時候就可以看到，不是facebook每天一直要推，而是我今天想要看g0v project就可以自己去找。
- clkao：欸不過現在那個手冊有，想像的Target Audience嗎？
- ael：手冊現在傾向的 Target Audience就是……做科技政策的事務官或政務官跟科技社群的
- clkao：對我說社群的部分。
- ael：你說社群的target audience嗎？
- clkao：對，什麼社群？
- ael：現在想像是網路上鬆散的科技社群，不一定是開源的，所以比如說g0v 啦，登山啦、或者是新創，你可能很難抓新創這個社群或是這個圈。你說還有哪些嗎？
- clkao：Mozilla?
- ael：Mozilla 也有包括，就是原本我們這個開源社群，就是開源社群之外應該要再包括其他的科技社群，可能是maker 也是開源的，就是像類似maker、無人機 ，然後比如說AI，他們可能不一定有開源，可是在網路上有active的討論群組，或是區塊鏈也有一些active的討論群組，那我們現在手冊的想像是，這些人他們以前沒有法人代表，現在也是沒有法人代表，但是如果有一天他們想要……如果有一天台灣不能……停止交易比特幣的話，他們想要出來發聲的話，他們可以透過手冊建議去做倡議或是去影響政策。所以手冊現在，那天跟俊達要了Green Peace的訓練手冊，就是說你怎麼去advocate跟行動，然後問了八六某些網路的建議這樣，然後接下來會想要訪問登山社群的Rex他們，因為他們本來不覺得自己跟政策有關係，結果後來政府因為有政策出來，所以他們就變得必須得跟政策有關係，不然他們權益會受到影響。對，現在手冊的方向比較是這樣，那工具整理的部分就是，你可能就不太是我們工具的target audience，就你平常不會去整理、你沒有時間去整理大家要討論那麼多的東西，所以我們現在要找、明天要問孝先就是他整理比如說，網路中立性啊或是Uber啊，還有之前各種服貿懶人包的時候，他整理這些網路意見會有什麼樣的process，跟我們的工具可以幫到他嗎？我們工具會比較for他，但是如果你要用的話還是有在PDF上comment的這個功能。現在可以host PDF，所以那天Join平台那樣的PDF可以直接上傳然後可以請大家comment。
-  
- 1:05:43 
- 
- clkao：但是譬如說Peggy他整理三個討論的……有辦法幫到他嗎？或者是他整理出來的有辦法呈現成其他更容易……
- ael：現在還沒有辦法呈現成其他人更容易閱讀，但這是目標……對就是能夠呈現給其他人更可以閱讀，現在呈現有點糟……
- clkao：就是我想要很快的有不同意見overview，那為什麼誰support這個意見為什麼……
- ael：對，但是我們現在具體上不知道這件事情該怎麼系統化地做，然後讓它被呈現出來。就我們現在也是想像說，因為以前大家整理的方法就是複製貼上之類的，所以現在想要知道孝先或peggy這些人他們整理東西有哪些process，這些process哪邊可以透過工具自動化然後幫助他們，可能還是沒有辦法幫餵到……. ，可是有沒有辦法用工具之後他們的effort會少一半，然後可以更快這樣。那我們現在實作上也是沒有想法，但是有個想法是他可以變成spreadsheet ，就是你tag之後你下的tag就變他的header，然後當可以dump 成 spreadsheet 之後可不可以做後續其他的，那技術上這件事情可以做，但是…….因為像那天跟沃草王希聊，他就會說層次很重要，可是他也就是不知道怎麼拉出這個層次，我現在已經遇到很多人跟我說層次……
- clkao：他說的層次是什麼？
- ael：就是比如說他們現在做中正紀念堂的轉型正義的工作坊，大家會提出非常多的問題，所以他個人會去拉那個議題的level，去把不同的意見去歸類在不同的可能是維度或是……大家會講層次的話就是有一層一層的，例如你這個問題是討論我們需要轉型正義嗎？為什麼需要做轉型正義？轉型正義到底是什麼？怎樣可以算轉型正義？那另外一個層次就是，好我們都同意要做轉型正義了，那中正紀念堂該怎麼辦？然後中正紀念堂代表的是什麼，或是我們討論中正紀念堂的轉型正義的時候需要哪幾個category，然後再下一個才是要不要拆銅像之類的。
- KL：就是一個議題他其實有很多相關的面向……
- ael：你有的時候先回答了某些問題，後面問題才有辦法討論，但是其實大家很容易直接進來就是說，要不要拆銅像，直接進來就說，喔這個空間應該要保留，因為他就是讓大家有運動的空間很棒什麼之類的，然後建築很漂亮之類的，而沒有去討論到這個問題的前提這樣，所以……那現在這就是人工啦，你問他他怎麼做的，他說他就是大概看一下，然後把它整理出來這樣。
- clkao：但是……你希望工具是不特定的人一起用，還是每一個人自己用自己的？因為你crowd如果是crowd去訂那個category，然後你某種程度讓他的hierarchy出現，是不是就類似像剛剛那樣的結果？
- ael：我們想像中應該像是大家一起用，然後我的想像是會去定這個structure的人很少，就是你所謂主動提供比較具體意見的人很少，所以……有沒有什麼方法是讓大家、去引導大家去下一個hierarchy的tag，或者是我那天提了一個想法，但還是不知道……還是可以讓tag跟tag之間可以有指向的關係，就是這些tag是在這個tag下面，所以我可以用tag去拉……
- KL：tag的意思應該是指向這件事情，設定指向這件事情，我覺得還要再看……
- clkao：設定指向還有正反。
- ael：對啊就是，正反是什麼意思？
- clkao：就是你同意這個，或者是接近這個，tag relationship。
- ael：但我們有想過如果他comment在旁邊可以vote的話，那是不是每個comment可以接到pol. is的去拉，就是等於每個comment都是pol.is那個statement，然後他就是vote……三種嘛，對，然後如果是這樣的話，因為那天陳東升就問我們說，那你們這跟pol. is有什麼不一樣？我們說 pol.is沒有辦法、很難看到context啊，只是你的那個statement是獨立於其他statement而存在的，你沒有辦法看到這個statement的研究數據跟什麼，那我們這個可以結合的話，他可以回來看當初這個statement是在什麼脈絡下被產生出來的。所以具體來說我們還不知道要怎麼讓他看起來比較清楚，可以幫助大家整理這些關聯跟層次的東西。
- clkao：那hychen說什麼？
- ael：什麼意思？
- clkao：hychen 有什麼想法？
- KL：hychen 說先把 sense.tw 的功能做完。
- ael：對我們現在一個scenario都沒有辦法完成。
- clkao：什麼scenario？
- ael：就是……使用者會用我們的工具去標東西，目前主要還是我們自己人在用，還沒有找到一個好的testing case，或者是，就是他覺得這個東西他真的可以用這樣子。那現在hychen 有，雨蒼那天丟了一個意見書。
- clkao：哪一個？
- ael：跨部會什麼？對對對，然後hychen就有在用那個在PDF上標，然後comment。
- clkao：那結果怎麼樣？
- ael：他昨天是才做這件事，然後目前應該其他人沒有跟進。
- clkao：你說其他人是誰？
- ael：就是其他想要加入討論的人，沒有用這個方法跟進。所以我們還要……
- clkao：對，其實從文件的pol.is然後再去做hierarchy，就是我最早在想說你法案上到底要怎麼討論的一個做法，那我的想法大概是，就是你有一個關於這個主題的conversation，那大家還是一樣，就是針對上面做statement跟回應，那再來就是這個討論有很多artifact，就有很多文件，那這個文件你可以針對裡面，你是highlight起來，對他做statement，那同意或不同意，那所以meta conversation就成為這個，detect 這個hierarchy就是一個top level的東西。所以你可以看到就是說針對文件裡面的某個statement的yes no，但是他上層，對於這整個議題的meta conversation是什麼樣的態度表態，所以就先做一個兩層的conversation。
- ael：我現在有點聽不懂……喔，然後就是comment是第一層，你說的meta conversation是……？
- 1:15:26 
- clkao：就針對這個議題，例如說這個跨部門資料這個議題，那我有想法就是要使用我的資料要受我同意，那這個是關於這個議題的討論，但是有關於這個辦法的討論，他有一個辦法，那這個辦法是這個議題裡面的一個文件，對不對，那對於這個文件裡面我可以一樣highlight起來說，我覺得這個條文不合理，但是你把這個conversation兩個把它變成……像你可能也會有多個文件，那多個文件可能是……我再舉另外一個例子好了，假設我們今天談的是例如勞基法，那針對這個議題大家有像pol.is conversation，可是針對勞基法修改的這個文件，實際上的不同版本的文件，他是多個文件對不對，他可能是十份草案，那十份草案我都可以分別去找，我覺得這個合理這個不合理，那你這樣是不是就會一個metric，就是原來這個大的 conversation 跟裡面的這個 individual 對於實際的議題，實際的這個草案內容的意見的交叉比對，那你也許就可以呈現例如 32-1條對於這個，那有人說這個排班間隔，就是這樣是不合理的，那很多人同意。原來 pol.is只能讓你看大人物對不對，那我們變成從這個議題來分 group去看討論這個議題的人，在整個 meta conversation裡面的最重要的共同意見是什麼。就是從這個 statement 的yes no 來切下面的 group 的分法，你懂我意思嘛？
- 
- ael：我還是不太理解，因為現在pol.is是用演算法去算哪些人跟你同意的意見比較相近，所以你現在想要看是，例如今天針對什麼第 32-1條，for yes no 的人，他們回去更大的那個picture 是哪個群體的人嗎？然後你是說……
- 
- clkao：或者是你從這邊再去分……
- 
- ael：像 pol.is 是看不到，還是他不要給你看。
- clkao：看不到啊，因為他只做一次 PCA 嘛，他看哪個是dividing question，那我們可以做的就是說我們做 N 次PCA但是我們先把 dividing question 定成現在這個 context。你知道意思嗎？
- 
- ael：OK……嗯……了解。
- 
- clkao：那怎麼呈現就可以再想想看，或者說你想一個具體的例子，就是，雖然同意修法的是這群，可是他們對於這個議題又有很多不同的意見，你想一個 scenario 來看看怎麼呈現。
- 
- ael：其實我以服貿來說好了，都上街的那群人其實反對的東西可能很不一樣，有人是反對......貨物貿易協議可以，服貿不行；有人是我就是不要跟中國，跟中國就是要賣台；有人是反對程序黑箱；有人是我反對國民黨，這其實……結果都是在街上沒錯，但是其實大家的立場不太一樣。或是同性婚姻也……
- 
- clkao：但是那個用一個 conversation 就可以表示了對不對，那我們現在是因為是議題搭配實際具體政策的討論，所以你要拉出兩個維度來。
- 
- ael：了解。所以就是具體的……
- 
- 1:20:00 
- clkao：就是廣泛上來講，大家對於這個……
- ael：我懂了，就是不是只有針對議題去做討論，而是具體的文件的……
- KL：hypothesis他那個comment他有針對這篇的statement做意見的comment（Page Note），或者是你可以針對其中一兩句去做 comment，意思是一樣的。
- clkao：沒有沒有，我剛剛講的是比這個更多。
- KL：我知道，當然是更多的啊，但是這種類比就比方說，針對這個東西一開始的初步的意見或者是想法，但是他有可能大方向不同，但 其中有一兩個句子他覺得是對的，然後你可以去交叉比對，或是支持的人他到底在這篇文章裡面某幾個部分，他是有一個趨同性這樣子。
- clkao：譬如說這樣講好了，譬如說勞基法我雖然不同意修法，可是他就是要修了嘛，那我還是可以對他修的內容來表示意見嘛，他修應該要修成怎樣。
- ael：因為就是說based on一個文件或是based on 一個fact來討論，例如我可以generally 支持……我反對 Uber 怎樣怎樣，但是你也要回到哪一個，到底是怎樣的條件，比如說法規怎麼樣改，你可以接受不接受。而不是只有 Uber 合不合法，Uber 合法會有很多種方式，所以比較有點像要落實要具體的討論。所以如果再換其他議題具體來說……
- clkao：先想一個測試的 scenario 好不好？那之後要想更多用途跟呈現，我們就固定......
- KL：我覺得 Group 這個功能很重要。
- ael：這功能還是要……但是 clkao 是說有個測試的scenario然後這個scenario……
- clkao：我們未來討論就是固定……
- ael：固定可以用這個 scenario 一直討論，然後也可以找這樣的人測試。
- KL：我同意，只是我覺得在做這件事情有一些功能要先有才......
- clkao：不影響啊，我們現在討論就不用一直換主題了，我們就用同樣一個來講。
- ael：反核呢？
- clkao：看你要是在這個專案的 scope 裡面的還是要不要的 scope 裡面的，因為核能會在能源白皮書裡面。
- ael：喔喔你說不在那個 scope 裡面。
- clkao：對，你也可以故意找一個不在 scope 裡面。
- ael：我們沒有找在 scope裡面啊，我們scope裡面要放就是AI或數位國家，可是 AI 要再具體一點就是 AI 的什麼……
- clkao：你說那個教育是真的嗎？培育人才，是有這個議題嗎？
- ael：之前有可是我不知道現在有沒有開。但是好像沒有開這個會，而且 AI 教育人才也不在計畫 scope 裡面，因為那是教育部的事。
- clkao：沒有啊他這個在科會辦……
- ael：是啦，但會壓到教育部的業務啊。
- clkao：沒有，產業人才培訓是在工業局，然後還有勞動部也會來參一腳，因為他想要失業的人學習一些技能，教育部比較是一些常規的教育。
- ael：AI 教育這個問題存在，但我不知道政府有沒有要為這個開會，然後我知道大家對於……
- clkao：有啦，像我聽說有人直接去開會。
- ael：到底要怎樣才能真的教育出真的 AI 人才這件事情大家有非常紛爭的看法。因為其實沒有人知道……
- clkao：最好是那個團隊大家意見都分岐。一個題目......
- KL：內部可以先吵架，然後……
- clkao：對，然後我們怎麼讓它有效的呈現大家不同的觀點。
- KL：光這一點、這個議題我就沒有意見。
- ael：AI的進入門檻比較高，可數位國家又很空泛，但是上面他就是希望我們可以做 AI 跟數位國家的討論。
- clkao：好啊那就找裡面的一個子題啊。
- ael：我覺得隱私權這件事情，我可能會跟 hychen 吵架
- 
- clkao：對啊，你們就吵一吵，然後用工具呈現大家的場景，還可以測試其他的工具，因為arguman你有聽過嘛？
- ael：arguman？有。
- clkao：土耳其的那個。
- ael：但是我沒有……我沒有很努力地查。好，好那我們現在想個 scenario，應該差不多就是這樣，差不多一個多小時，有兩層的conversation。對，然後手冊本來是十二月底的KPI， 但是大家都遺忘這件事情了。
- clkao：那怎麼辦？
- ael：現在就是一月底前先寫一部份給社群的，然後二月底再把給政府的寫完。我已經不錯了，我已經開始了，B 分項完全忘了這項 KPI，他們要寫一個民眾語彙腳本的手冊，他們的 KPI 也是壓十二月底，可是他們還沒開始。
- clkao：那但是這個手冊可以，你們要廣泛參與嘛？
- ael：可以。
- clkao：吃自己的狗食一下。你們可不可以根據這個手冊的 principle 讓大家來參與這個手冊……
- ael：可以，但是，是，對，然後 hychen 就說我們可以根據這個手冊來run那個APNIC 的 vote，就是如果你想要在這個手冊中新增段落的話，你就要提一個proposal，過一段時間大家可以來看資料。對，但是我發現一個狀況是，你通常沒有一個比較好的草稿的時候大家……
- clkao：對啊，一定要有一個 draft，除非你是key question，比如說剛剛講的開會前哪些、還有沒有什麼其他人，Phase你可以先做。
- ael：我 phase 1，我下禮拜之前要先整理就是，你跟誠夏、TonyQ 跟whisky的訪談，然後先整理出一些……
- clkao：whisky 已經訪完了喔？那怎麼樣，他有沒有很兇？
- KL：他沒有很兇。
- ael：他跟 hychen相談甚歡。
- clkao：真的嗎？
- ael：真的，因為 whisky在講知識網， semantic web，所以我跟 hychen一點就到了，然後我們是約兩點，然後 whisky 大概一點四十就到了，所以他其實是從一點四時開始聊到七點，很可怕。
- KL：太可怕了。
- ael：對，所以其實他們相談甚歡，譬如說 semantic web，或者是資料要有一些基礎建設之類的，還有跟政府的 web 要可以被 Google 搜尋到啊。
- KL：還有政府執行單位的一些人啊、問題啊，或是幕僚啊。
- ael：所以我應該要禮拜一目標是先有一版是可以給大家加的，然後現在有一些比較好的template 但我不知道能不能公開，像 Peggy 他們其實有整理一個 PO 會議成案之後的問題集，就如果你是一個政府的人，你成案之後應該要做什麼，要問哪些問題，但是……對我的電腦現在……我的電腦真的好慢啊.......好那我就先停止錄音吧……
