* Profile
個人部落格 or 評論政策流程公開演講影片？
個人部落格：http://lucien.cc/ → 不過上面多是分享開放授權應用的評論與資訊，和政府與民眾互動相關的議題有限！
開放政府觀察報告與談 → https://www.youtube.com/watch?v=gQ0pI---Wio
過去三年參與政府會議與角色
e.g. 開放資料委員會（行政院、國發會、文化部、陸委會）
e.g. 開放社群評論的 Google Doc, pdf 、公開臉書貼文等→可參照附件「自由開源軟體推動策略建議書」，「四、建構發展的基礎架構－－政府行政的角色與責任」這個章節，沒有直接相關，立場如何切入或許我週五下午可以口頭補充。
過去三年政策倡議與遊說
e.g. OCF 拜訪唐鳳 sayit 紀錄：https://sayit.archive.tw/2016-10-25-%E9%96%8B%E6%94%BE%E6%96%87%E5%8C%96%E5%9F%BA%E9%87%91%E6%9C%83%E8%88%87%E5%94%90%E6%94%BF%E5%A7%94%E4%BA%A4%E6%B5%81
e.g. 開放資料社群討論 hackpad：
臺中自由文化授權條款 1.0 版：digitalculture.tw/license/TCFCL
臺中開放文化授權條款 1.0 版：http://digitalculture.tw/license/TCOCL
常態在開的是開放資料政府諮詢委員會
修改規則後原則是一年兩次。
最近有新的計劃是國家歷史記憶庫，例如開放授權。
* 訪談問題
目的：提供政府與線上社群協作的建議、SOP 參考、原則參考 怎樣蒐集社群意見、倡議產生政策影響力
* Q: 簡述政策參與（促進）的經驗。你參與過的政策形式，什麼樣的方式參與？與政府開會的角色是什麼？ 用什麼架構分析政策形成、公民參與？
過去在自由軟體鑄造場，政府單位設立想要跟技術社群合作的平台。
早期以技術會議、專家會議
早期以中介者
現在是社群參與者的角度
第一個對政府建議如何跟科技社群溝通。我的本位是公眾授權的研究。訂立一個原則大家都去研究。
做開源專案，平台不是最重要，重要是內容。建立開放授權的東西可以移轉到很多平台。平台
重點不是政府建立平台，而是利用現有的平台。
早期在協助經貿國是會議線上參與的時候，大家就說你要溝通可以，要有社群熟悉的平台。政府近年有個問題是自己架平台。例如在鑄造場，我們有去美國跟sourceforge 聊。那時候國內國外的平台就是 sourceforge，目前比較退流行。鑄造廠 1999 年開始討論，有個想法是成立 sourceforge 亞洲拓廣站。後來因為開了專家會議，很多專家不一定是專家，德高望重來，執行機關不照著做就得負擔責任。行政機關就會照著專家建議走。
今天如果做互動平台，如何挑選建議？要改變專家會議的形式。現在傳統的形式就是找專家學者來開會，但我覺得專家會議應該要慢慢淡化掉，通常一個太尖端的事情無法透過專家會議，無法給你真正讓你事情起來的建議。如果你建議一個所謂的交流平台。
早期在做 open source 的領域，志展、Jserv 很行，都沒有學歷。後來只能統一說明，沒辦法你拿公家的錢得交證明。幫他們存資料起來。讓真正有做事的人發言。
平台必須要取代專家會議。有些開不好的專家會議，對公眾政策的背書。
反對太形式化的專家會議。例如去找紀錄可以自己負責的專家。行政院」國發會、陸委會、文化部。國發會已經做逐字稿。行政院會去蕪存菁，幾乎會帶到。文化部就是一張紙。外部會議如何讓他如實的呈現，有些是內部會議。例如在改課綱，你只會看到發言大綱。以前這樣做是對的，以前的理由是匿名才能讓你暢所欲言。很多匿名帶來的是不信任感。如果以後要開專家會議，盡量走越開放的方式越好。
我參加了這麼多開放資料的委員會。有一個委員不同意就不能做這件事。如果可以的話，盡量是找願意的委員來開會，變成實質的。
另一個方式，利用既成的平台。例如，在原來的地方開發。政府想要跟科技社群對話的話，就是先到科技社群跟他們對話，而不是開新的地方再叫他們來。即使透過說服其他人在新平台開專案，只會丟 patch，不會成為真正互動的場域。如果政府在哪個地方需要做民意的吸納，那政府要變成參與者。平台的管理者必須要是中立的。政府必須要參與，讓平台要可以自治。
你是政府單位，你反而會比較不受信任，不如委託中立的法人，或是社群自治，參與這個平台的互動，沒有特別理由的話，不需要政府去架一個平台。
這個計畫是要做科技政策白皮書。
如何判斷有價值的專家？
現在給的時間和資源又很少。
美國的陪審團，有赴日之旅費，還供吃住。通常你只有很短的時間，很多我推掉。
有沒有讓他有準備期間？有沒有可能事後做補充？
公務人員常常臨時被交辦。
我的期待是，這件事很重要，可以掛特別專案，可以有一到兩個月來做。大部份的專家會議流於形式
有些我不會推的話，就是會造成決定
行政院XXX資訊採購法會三天前才通知我。你不去了話那個就不會過，我推掉其他事情去。
hychen: 你怎麼判斷這個很重要？
誠夏：是科長跟我說的。
hychen：我覺得是有這些專家會議沒有做到完整 inform 的動作，例如提前讓人在網路上討論都沒有做。事後要討論也很難。
誠夏：類似狀況在開放資料委員會也發生過。民間代表，clkao 跟我，在五個工作天之前提供討論事項。其實連行政院的這種會議，大部份會議有調整，就是拘束開放資料委員會。最後有統整給與會委員看過，看有沒有要補充的。
目前沒有，實在講，建立這個標準，也是困難重重。
真正重要的事情能不能多給一點資源？
hychen: 輿論一出來，政務官就會有壓力，於是就要開專家會議。
誠夏：可以把騎乘拉長為一個月的討論。有壓力就是要處理。建議跟期待，就是還是要有一個月兩個月的追索期。如果你要開專家會議、網路社群，是實質、長期。討論過程能盡量公開就盡量公開。不願意公開的就不要找他來開會的。專家會議就是有爭議性，需要大家發言。今天如果可以做到這些原則的話，大家對於自己講的話就是要負責。
by default open
open source 早期在政府的採納是例外。現在普遍使用上面是，可以用，但是要主動告知。以前覺得要保護專家身份才能暢所欲言。
像是唐鳳在教育部當委員的，去提了例外，不斷去轉移典範，原則上是公開的，另外有理由才不公開。才能讓民間意見吸納變成實質化。不公開就太形式化了。
像是資安管理法，我就不太去了，一是我所知有限，二是太形式化。我不能去，但我發現出席名單還有我。會影響願意給意見的人的參與動機，一個調整的方向是公開的。
** Q: 有去過公聽會嗎？有人會覺得都是在作秀阿
   有啊，我會去著作權法的公聽會啊。有啊，位置坐不下，關係人來很多人，他就是講那一套。公聽會是行政法程序上的保障。公聽會現在意見越來越沒辦法吸納，很多是發洩情緒。我的意見是，大家應該要增加網路公聽會。例如現在選舉制度，投票或是連署是不是能夠增設網路連署？他當然有很多的原因，中選會的意思是他們是想要做網路連署，他們成本比較低。因為網路有自動驗證機制。很多連署票會無效，就是戶籍填錯之類的，最後還要人工驗查。對於行政說負荷可以減低。但是不是所有人都可以上網。但態度是未來可以兼容。
   公聽會有相當價值，但不是只有政府召開的。只要讓網路公聽會有程序，也能被列入。現在只有實體的公聽會。
   著作權法孝先有建議去vTaiwan。但智慧財產局不習慣去。
hychen: 網路意見咨詢都應該有網路團隊 support。
cc 組織會牽涉到著作權法修法。歐盟對於 cc 的修法，都可以遠端。例如 cc Autria 可以遠端跟歐盟報告。歐洲議會在處理重大問題的時候，可以遠端提出意見。透過虛擬的方式成數意見。不知道有沒有標準流程。
對於 vTaiwan 來說如果他可以擴大，我很支持。
Q: 對於一般科技社群有什麼建議？
需要學習他們官樣的方式，給建設性的建議。就是再提建議的時候，要提怎樣可以改善這個狀況。很多就是罵。但是對公務員來說就得省略，回應你也怕動輒得咎。JOIN 八成以上是情緒表達，沒有提出實質建議。簡單來說，你發言的時候，提出批評與建議改正的方向。這樣公務機關比較好改正。我覺得就是單純建議。
這是可以鼓勵的。
公聽會有時候疏導就是讓反對者去發洩她的情緒。如果想要公務機關調整，要有建議的方向。
著作權法大部份人就是表達情緒。例如大陸的盜版政府管不了，例如政府是不是可以流行音樂中心請大家常態性的做表演。有些事情是公務人員沒辦法去處理的。
例如上次去參加 JOIN 平台的改革討論。同樣一批人，丟到首長信箱與JOIN 平台上連署成功的，得到的回應是一樣的。他是什麼？如果要最精準地講，他只是一個溝通平台，他不是行政程序法的一環，他頂多只是陳情。一個人跟五千人陳情的差異在哪裡？這代表五千人有相當能量的。其實一樣的答案是不合宜的。
我就算連署了，政府不聽能怎麼辦？那政府可以怎麼辦？那政府應該被課責的。
現階段可以不管 JOIN。有幾個階段，現在需要開公聽會。首長信箱有這麼大的威能，是因為內部有行政規則一定要回。要建立像是首長信箱一樣的規則。
hychen: 行政規則中央能夠影響地方嗎？
誠夏：警政是一條鞭的。內政部有權力，但是會尊重台北市首長。如果不是這樣的話，就是尊重地方自治。有跟簡處長聊過，不是一條鞭的，無法行政院國發會要求地方政府一定要去做。如果這個法律制定有一條鞭，例如教育，中央政府定的行政規則就會影響到地方。
如果網路收納意見越來越重要的話，就是慢慢去訂行政規則，要當一回事的。
正規程序就是實體的公聽會。
網路可能比較即時，更會影響輿論。當這個東西變成常態，就可以進入行政程序法，成為制度的一環。
最近衛福部本來要做一個決策，同性戀的矯正醫療不應該再進行。但是後來反同的聲音很大，就在 JOIN平台上做連署，目前衛福部就先緩下來。充其量只是一個陳情。但是衛福部的意思是，我就先不公布禁止的指示，先做後續的討論。至少我做了外部專家會議結果，給 JOIN 平台回覆後，才會去推結果。我個人覺得是成功案例，代表 JOIN 平台上的意見獲得尊重。
JOIN 目前就是陳情的平台，沒有任何阻斷行政程序的效力。訴願也沒有阻斷行政程序的效力。從公務單位的理解，吸納意見還沒吸納玩，院長就下指示，當然要聽院長的。那可以做成縮短期限。
政府如果覺得這件事情重要，應該要列入彈性規則裡面。以前就是一個口令一個動作。
他們需要一個規則。現在是統一拉長，之後可以去思考需不需要統一規則。重大政治爭議要不要調整規則。JOIN 上面，重大選舉之前就會停掉。
hychen: 我覺得重大政治爭議就開一個特區給他。
誠夏：大部份人給 JOIN 平台的意見是，吸納意見的功能。
ael: 上次的 JOIN 平台會議有會議記錄可以看嗎？
hychen: 通常會議是連續的，但是沒有地方可以看上次的會議記錄。
誠夏：開放資料諮詢會議，是要統一開在ＸＸＸＸ。現在的流程就是告訴你，定稿前會給你看草稿，會給你看紙本的公文，不會給你看電子檔。
hychen: 大部份專家會議是連續的，但我沒辦法每場都去。但我沒辦法看到其他場的會議記錄。所以你的立場是調整現有 SOP。如果今天認為這是很重要的，要把最後網站公開的連結提供給你，要看到系列的討論。如果有這樣的建議，他們比較會去做。這些 SOP。政府開放的諮詢會議已經做得比較好。國發會有個統一的規則「政府資料開放諮詢小組設置要點」https://www.ndc.gov.tw/cp.aspx?n=E8E2E9E3E4EAE332
我的態度是希望他們早點開放。如果是我自己記錄的話，跟他們開放不一樣的話。有體系的備查，還是要主辦單位主動的去做。
hychen: 應該要再加上好處是什麼。前期可以縮短專家會議的時間。
誠夏：現在去隱瞞委員的身份無助於糾紛的解決。
hychen：除非你是要諮詢，大家礙於情面不會講難聽話。
誠夏：立法院可以直播，但是協調會有幾段可以靜音。沒有特別理由就開放。
hychen: 突然想到應該用 AI 來做唇形解讀。
Q: 參加這些政府會議你會帶到社群意見去嗎？
用OCF 意見的，我會在 slack 丟，我會先丟我想要講什麼，然後再請大家給意見。通常不會有意見。
參加 cc 的，我會在 mailing list 裡面，做一樣的事情
草稿，放到 wiki page，說我要發表的，其他人有沒有意見。舜舲和妝品叡會提出意見。
我會在特定社群議題社群丟。
主要是我自己的意見，會有根據之前跟大家討論的意見做發表。
可能是在 OCF 我還沒找到適合的群。我可能要去資安的社群才會給我意見吧！有時候我發現不是我的領域，於是我後來就不去了。
hychen: 我被去找去參加專家會議，也不會跟我解釋為什麼找我。以前我們覺得 email 是個資，不會隨意寄陌生 email 給別人。
誠夏：有些專家會議我也不知道為什麼會找我，有人在網路上開玩笑，這次找來討論的人怎麼去挑選的。是最近有罵過的人嗎？
經貿國是會議就是先找中研院資創中心，因為 g0v 黑客松都在中研院資訊所。陳明憲就拒絕了（陳昇瑋、自由軟體鑄造場）就去找資訊所所長。翁啟惠說請資訊所所長勉力幫忙。就找到莊挺瑞（？）跟楊德年（？），比較了解社群的互動。 OK，中研院先開幾次實體會議，中研院先開了前三個活動，例如國發會希望拿到與會者名單，我們拒絕了。中研院以跟社群當朋友的經驗把你們聚在一起，那時候示範基本的社群禮儀是什麼。那時候的角色是中介者。
有兩件事情我們很堅持：第一國發會不能拿名單，例如前三次會議不會要求大家表達身份。不熟之前先建立信賴。第三，勸國發會，容許社群自己錄影、直播。yutin 那時候就自己來直播。我們有勸政委的秘書，不要去阻止她直播。盡量把他導成。例如不要先政委致詞，跟我們一樣排排坐，去階級，輪到政委發言。你找我們辦就是希望大家可以講話。
經貿國是會議最後是沒有什麼成果的。但是就開啟對話他是有成果的。例如接下來有些人慢慢進入政府機要缺，開始調整，是有成果的。開始讓民間社群與政府部門產生對話。例如那時候政府和辦公室一直想要找代表ㄝ網路社群有意見領袖但是不會有代表。意見領袖會引起話題震盪，但是沒有網路代表。後來就理解沒有代表，社群代表這幾個字是不能講的，開始理解是社群參與者，那至少是一個開始。
 
我在想 cc global 社群裡面，還是透過陳情、找支持的民意代表、遊行的方式。例如他們抗議 TPP，在歐洲的部分就是找開放授權比較親善的歐洲議會代表，例如舉辦公聽會、演講、說明。
 
不外乎就是那些方式，因為政府他必須照行政流程。如果你真的要直接影響到他，你要去知道那個流程。你可以透過發表意見凝聚共識，然後再影響。
 
我其實沒有特別想到成功案例。
 
他可能還沒辦法走到那步。透過網路吸納意見，變成正式陳情的平台，是值得去走的目前還不行。
 
境外網站封鎖，很快就組織一個網路頁面，提供立委的網站去轟炸他。這算是網路組織發表意見直接影響到民意代表。這不是個政治流程。如果你是說透過網路吸納。
 
例如割闌尾。後來是化成正式的行政流程。他本來是個政治行動，用網路作為一種載具。
 
hychen: 現在只有一種管道，你是網紅，然後媒體來報，走看報治國的路線。
 
想不到成功案例，可能還沒成熟到那個程度。
之前在資訊所說 AI 三十年前就在研究了，但是三十年前做不出來。
 
我們可以想像，可以透過網路作為科技政策的形成。
網路意見可以吸納、可以被凝聚，可以去影響行政程序。
 
我的實質建議是可以開網路公聽會。例如公聽會是可以去回復的。
行政機關是網路是吸納意見，但聽不聽隨我。
唐鳳負責架中立的平台，蔡玉玲用政治資源要求行政機關認真對待。才有可能科技政策透過網路音量影響。
 
政府機關的實作必須透過政治力量。
 
蔡玉玲政委就比較知道從既有的行政組織架構，從上去做指示。但我的意見是，必要的時候還是需要從上到下。行政機關很簡單，有些需要上令下達。唐正偉的性格就是由下而上凝聚共識。
 
 
例如我有被加入一個 open hardware 的臉書社群。
但是政府在討論 3D 列印好像無法接觸到他們。這部分我不敢說我知道很多，你至少要有關注清單。例如找到 key man，可以去做意見傳達。釋出的這些資訊，這個群，你至少可以吸納意見。
 
像是 cc Taiwan，有固定在關注著作權修法的人。
像是智慧局
 
（手痛 again）
 
先強化連結
 
hychen: 政府應該要做 in-bound marketing，讓你的目標 TA 可以來看這些部落格與文章
誠夏：Linux 基金會的做法是，各個產業和公司，如果你想要投報給我，可以投。你可以把你有做 Kernal 的人的聯絡資訊留在 Linux foundation。如果要打官司，可以先私下處理。政府有意願要做，至少要有清單的建議。
hychen: 有 news letter。
誠夏：至少有一個地方可以投報資訊。key man 更新也會通報。
hychen:我後來的想法。
 
permanal link：至少可以分享給別人。
 
ael: 容易找到報名入口、線上意見投書的地方
 
聯經數位得到 data.gov.tw 的案子，網站有改版了。只是資料庫已經重新建新的。現在已經用比較 open source 的方法調整結構。我不知道你們的報告要不要帶到這個。他們開會議就是分享這個。例如台中市的數位治理局一直沒有成立，蕭景登希望能把政府的數位服務結構化。對未來跟網路社群互動是有幫助的。
