* Q: 簡述政策參與（促進）的經驗。你參與過的政策形式，什麼樣的方式參與？與政府開會的角色是什麼？用什麼架構分析政策形成、公民參與？
2010 年替代役：資訊系統，默契、信任。2014 年經貿國是會議。
蔡玉玲主導網路討論線上參與，找了資訊社群，例如高嘉良。不知道怎麼做線上參與
應該召開小型會議討論：線上諮詢平台討論會議 3-4 次
在網路公開資訊看到然後報名參加，是路人
在經貿國是會議期間，我提了一些網路參與的形式。例如，讓網友直接用視訊發表談話，大家覺得讓網友會輕易被代言。如果進來的人沒有辦法有一定代表性的話，議題很容易失焦‘。我提了一個折衷方案，直播是容易的，把直播的聊天室，直接把網友的討論，場內與場外互視。聊天電視牆。外部專家->可行辦法，有被採納。因為有去協助執行的關係，平價會比較高。會去執行概念，而不只是講講。因此會願意信任。
後來慢慢往內部走。
2015 年，在蔡玉玲當政委辦公室研究員，專案駐點，資策會。代表政委在數位事務上對行政院發言。那時候立場比較複雜，要權衡的東西就變多了。
2016 年年底，到嘉義縣政府，以專案辦公室去協助做智慧城市的推動。本質上以能夠持續跟著會議進行，協助各個局處去做該做的事情，給予諮詢性質的一個單位。
如果我覺得可行與需要，我可以面報縣長，經過縣長同意，就可以變成實際工作的項目。有但書但是比之前更強力一點。比較不如外部專家沒有實質影響力。

在這過程裡面，也同時擔任台北市社會局長期的資訊顧問。其實台北市社會局的資訊系統，對內對外的資訊專案的協調與決策。能夠深入到資訊標案裡去做，也有一定程度的執行。
同時在 2016 年下半年，加入新北市政府的青年事務委員會。因為新北市政府重視青年的意見。滿有誠意的，在我們提出要求的情況下，會讓我們跟所對應的業務單位對話。比較常見的情況是被諮詢的委員不知道怎麼跟政府單位對話。我比較特別，因為我熟知政府情況，密集跟研考會和社會局合作，之後我變成是常態性諮詢的對象。會找到當季的重點業務，然後協助他們資訊規劃。
* Q: 去經貿國是會議的動機？
  對政府的資訊系統一直都很不滿，政府作業程序數位化的進程。只是用一堆規則去阻擋參與，市場很封閉，做出來的結果很差。
  這個國家的資訊其實很強，但是政府永遠落後當下的做法，程序上不是資訊系統，是行政用而不是給使用者的 UI。會造成很大的行政耗損跟耗費。作為資訊人員，應該要用所長去幫助。
  政府用很大的數字去給廠商，但不太改善資訊系統，因為政府不了解資訊系統在外部發展的進程。內部主要的工作是確認事情有被做，而不是有把它做好。例如版本控制的概念，政府內部不存在版本控制機制。沒有人可以去維護 repository。
  在 2014 年太陽花期間，我們意識到我們必須要參與一些事情才能夠改變一些事情。我問題意識很早就存在，沒有參與就沒有改變。我發現其實卡住的點除了專業以外，要決定資源分配預算的是政務官，但是政務官對於資訊系統的認知及度有限。在 2014 年我要讓政務官理解資訊系統的價值，我做了兩件事，一件是協助柯文哲打選舉，一件是協助中央首長去思考資訊系統應用於政府內部。很多人認為政府標案就是鐵板一塊，但我不相信這件事。
  只是沒有人跟他們說外面怎麼做，所以就是用舊有的方式做事。
  變成是賽局，甲方乙方都是用同樣的方式。
  例如，從舊的變成使用者。
  例如 input 乾淨可以找公務員追殺，之後開放民眾填，資料不乾淨。他們很難適應設計。
  我試圖想要去
  很多人會告訴我你不了解你不明白，你不知道會擋到誰，如果這是一個理由的話，應該要   
  很多人進來看之後就不見了，
  工作上的協調會議，確認可以對外發表看到的東西，能夠把問題點對外說明。而不是家醜不外揚。

* Q: 以個人還是以社群進入？
比較像是以網路身份去參與的概念，份際有點模糊。每天會在臉書上寫下我的意見和會議。我會交代我在哪裡，跟誰拜訪，說了什麼。藉由把我對內說的話公開，如果大家有問題，我可能會去修正，或是提供其他網路上的不同意見。我去的時候是個人，但我的確用了社群的 title。這個 title 本身就是個虛銜。

專業、網路意見時，會強調以個人身份發言，協助他們找到更多同類型，他們想要詢問的地方。邀請專家演講討論、提供專家名單。

會定期蒐集 ID 和別人對我發表的意見有沒有什麼想法，有時候會做媒體投書，我會親自去參與底下的討論。在臉書上表態所有人都可以留言，對立是有界限的，不會把你趕走，絕對不刪除別人留言，確保大家可以看到不同意見。會把不同意見拉上原文。去平衡聲量。在網路上意見處理的部份。Facebook 實在是個非常沒有邊界，大家喜歡用隱喻的形式。如果檯面上講會對立，可以私底下講。

在網路上願意表達意見，我會假設背後是十個意見。背後其實代表一定不願意講出來的人。
至少我所接觸的群體意見模型。

重點是參與的人有沒有辦法表達
過去這群人對於網路意見就是極端、網友就是 abuse system。以前對於網友的態度是不能接觸不然就會被吞掉。後來會發現網友很多樣，是個集合體，有專家，可以在裡面把不會沒辦法表達意得見。過程其實滿療癒的，大家開始意識到是一個途徑、一個方法，不是只有惡民可以用。有了直播之後，大家...有一次在南投線上參與 vTaiwan，而有更多可能性。可以讓參與更擴大，避免關起來的會議有小圈圈的問題。

* Q: 開放的會議還是少數吧？
有變多，不是所有會議都可以開放。資源分配會議不適合開放。政策制定之前是 OK 的。

* Q: 如何設計好的線上公民參與機制？ 設計原則？ 好的案例？
現在問題是，線上參與之前要讓他們知道要參與什麼。
現在政府樣態，要公民發起議題，政府去回應，政府的成本很高。
像是公民用 JOIN 去發起，門檻很高，手上資料可能沒有，沒有人力去準備。可能也沒有專業評估報告。有時候是事務官的經驗，有時候很難去舉證，很難去報告。從外部去發起參與就很困難。這一塊的能量不會太強，整天在接新的需求會壓垮。
把部會有疑慮的，有大方向可是細節不確定的拿到網路上審議。例如 vTaiwan，這規劃的品質會比較好。溝通能量和事務官的甘願程度。個別事務官與政務官對公共參與的態度才是 key factor。前者是極大公益需求，或是很需要才能發動。
以既有部會意見提出
民眾需要提出一定公共性
還有很多文化上需要調整的
只有制度是不能執行出結果的
 
* Q: 政府如果想要找外部資訊專家進入協調？
必須要有使用這個系統的人在場，不是只有資訊部門的人在場。有很多事需要業務單位去追認的。真正要怎麼去組合拼圖與積木，是業務單位。
 
有系統的使用者、與規劃者的意見。
 
我曾經碰過很多委員，有沒有弱點掃瞄報告、防火牆去做 checklist。要這麼做的就是做成 SOP。要做的是討論彈性、客製化、資料庫，才是專業意見。例如有沒有常見的安全問題。
 
另一個前提是，要做資訊系統的諮詢，不能一次性會議。要至少三次，隔兩個禮拜，才能持續追蹤，動態發展。只有一次就沒有意義。必須要持續參與這個專案的規劃與諮詢。
 
資訊專家不是整天沒事來開會，但如果無法持續參與沒有意義。除非這個資訊專家是要做推廣、介接，那可能有機會，做後續的窗口。
 
資訊專家需要持續、在專案驗收週期持續參與。我每個禮拜都會開政府資訊系統相關的會議。
 
* Q: 如果是政策性的？
我覺得是一樣的，不是一次性參與，講求信任跟默契。必須在領域內投入足夠 committment，才能夠深入了解要推動的東西是不是有關。
 
有些在專家會議之外本來就是有非正式的諮詢，例如吃飯。
有些專家會議只是給出結論而已。
 
不應該倚賴非正式的會議。
 
* Q: 有人會抱怨會議無效率？
會議通知發出來後（一個禮拜），去追問承辦人會議要討論什麼是自己的義務。發起討論的人可能不知道需要提供你什麼資訊。像是在青年事務委員會，我們像議會，我們的需求都不同，需要跟他們要。寫出來是應該的，但是寫多細很難。
 
國發會為主軸，事先兩三天去要就會有。
 
我會提醒要給我電子檔，不用給我紙本。少數中央單位還是會覺得不提供紙本不好。
 
政府裡面需要破窗效應。他們才會去思考有機會可以。
 
至於各言爾志的問題，專家也需要思考自己要表達什麼，有時候專家的意見不再業務單位的脈絡裡。另外政府需要在議題內衝檔和折衝，去聚焦、對其，把無法對齊的再拿出來討論。如果就是讓大家發言，然後機關再出來回應ㄝ怎麼討論就是各言爾志。讓議題是動態性的討論。不然找專家來幹嘛？
 
有時候委員太兇，會認為沒做到這件事就是怠惰。我們應該還是退一步，要站在彼此共同的基礎上，追求往前進的方法。如果真的無法在共同基礎上討論，也要試著在對方的立場上思考如何達到結果。可以有不同意見，但不是 asshole
 
很多時候會議會被綁架，不同意就不能談
所有討論就會被卡住
應該是確保自己意見有出現在不同意見上
 
不能自己一個人不同意
如果有更多委員
 
通常事先不會知道有哪些委員
至少我不太會去看這件事，委員單獨行使判斷，我認為不應該事先交換意見
如果是重大爭議事件，
而且會對與會委員造成負擔
我會去問主辦單位目前的困難是什麼。
 
社群參與的前提：確認你真的符合那個會議所需要的專長，你的意見真的對會議有幫助。如果你沒有把握的時候，去跟主辦單位確認你需要提供什麼專長。例如我常常被找去講大數據。不適合的我會試著轉介出去。
 
如果會議內容模糊不清，委員應該考慮要拒絕掉，或說會議係向不夠清楚。委員需要表達自己專業的態度。
 
委員在去之前，主持單位與要討論的議題的關係是什麼。例如國發會是協調者。議題的所有者是誰？業務的主管機關是誰？要搞懂決策位階跟脈絡。你的會議聯絡人應該是你的好朋友。要去判斷，找你諮詢這議題的主事者是誰ㄝ誰是可以決定事情的人，才能做出有品質的討論。agenda 如何設定跟這些事情息息相關。
 
主議程在討論的過程說會有子任務，例如議題設定、臨時動議。通常是由在場主席在確認，如果你不知道誰是主席，無法進入脈絡。例如 Uber 我們特別尊重交通部，例如賣酒去尊重財政部。
 
搞清楚現場的權力分配
到底誰是要說服的誰只需要參考。
 
* Q: 進入非專家會議，比較廣泛的公民參與。vTaiwan 的網友參與有用嗎？智慧城市會安排公民參與嗎？
 
這題背後真正問題是，我們對於網路上的人們，對網友的信任程度到什麼程度。跟他們真實表現出來的程度到什麼問題。
 
如果來的人很高品質，就會很棒，加碼之後可能來的人品質降低。
 
我們信不信任群眾能不能做出好的決定？
 
群眾的意見能不能說服我們自己，或是我們願不願意把做決定的權力交給他們？本質上是我們允許群眾能夠跳過我們的意志或是西式我們的意志
。
 
有沒有用是第二層次的問題。
 
接下來大家會說要做公民教育，要有基本素養啊，好像在這件事情還沒達成之前，我們就不能做線上審議。
 
這個議題，還是主事者對於群眾的想像到什麼程度。
 
願意開放第三條審議的路線授權到什麼程度。多數情況可能用得不好大於用的好的程度。你問我單一制度有沒有用，很難回答。
 
在 vTaiwan 早期，是個相對可以被參與的制度。因為政府機關會不時把能做不能做，提出甲乙案。不管怎麼選，政府都是安全的。核心命題，就回到主席最後敲板定案。那個時候主席是蔡玉玲，可以決定，然後對群眾說明。必須要去回應這些問題。前提是，蔡玉玲相信大家討論的每個意見她都需要回應。他相信做決定的人有義務去解釋他為什麼做這個決定。本質上是覺得做這個說明。
 
有些人不相信做說明，而且會覺得會帶來更多批評。我相信不管如何要做這個說明，這樣才能確定通過的東西是經過大家看過的。
 
群眾能不能回應這個期待。這三個會是複雜賽局。
 
我們的匿名討論平台。
在會議上 sli.do，那個平台，搭配 pol.is ，多焦點群組 pol.is。讓專家跟網友去表達真實的意見。但是匿名的比例可以下降。po.is 要拉出的是群體的圈圈。vTaiwan 比較像是逐點討論跟資訊揭露。跳脫利害關係的意見表達，再加上主事者的民眾授權。是審議中必須要有的。第五個要素是必須接觸到利害關係人的推廣。現在我們還沒有參與的普遍基礎建設。
 
1. 主事者授權
2. 匿名表達
3. 分析利害關係人
4. 意見揭露
 
PDIS 只做到意見揭露。PDIS 只是確認每個部會有接到事情。把過去政委做的事機制化。
 
以 uber 為例，乘客、Uber、計程車、交通部。
匿名不只是匿名，而是利害關係人可以跳脫自己的身份去說話。但是匿名的意見需要一定程度降低權重。匿名高於實名會導致會議傾斜。
 
vTaiwan 的意見，會每兩個禮拜開一次會，去找各部會來，review 問題。給各部會政策上的空間，政治上用政委放給你，用專業事務官去給專業判斷。
 
網友影響有，不會有直接。但是內部政策可以有更均衡的分配。常常是來不及去研究它。就像是 Uber ，我們那時候在推的時候，三條紅線，台灣版的法規讓 Uber 可以落地。當時我們請交通部去研究的時候，2015 年三月，要研究到 2016 年 12 月。就算人民決定要做多元化計程車，還沒研究之前無法真的上路。可以達到及早去評估。可以知道立場在哪裡。線上設立公司那個題目常常是經濟部從來沒想過的事情。
 
線上設立公司怎麼出來的？可能從閉鎖型公司討論延伸出來的。有可能是行政院青年顧問團。
 
很多政策是被剛性否決，連想都沒想過。如果他們覺得沒有被剛性否決的時候，就會比較 open mind。
 
Q: 政治空間是政委撐出來的，不是外部專家撐出來的？
其實是院長或是立委撐出來的。
 
（台灣實務是總統不能逼著行政院長做事）
 
真的決定事情能不能做的是行政體系。
必須在既有架構下拉出東西來。
 
所以行政體系跟手掌有一定程度上的拔河。外部的人常常會覺得總統一句話就可以決定很多事情，但只能決定大方向，細節沒辦法。
 
參與公共事務基本前提是討懂國家權力運作。
 
要怎麼搞懂？
 
不懂很難施力，沒有參與又很難懂。
很多人一來參與，發現他不懂遊戲規則，就跑掉了。
 
青年事務委員會授權不足。外部委員很少，在他們都是在被設定的事物底下。對外溝通型，特定議題面的，效果和效用大幅降低，都討論沒有標準答案的東西，不會有共識，就不會有結果。
 
新北做的比較好。外部委員為基礎，20 位，7-8 位是內部，從高中生到三十幾歲各行各業都有。每個委員都有個別跟首長對談一個小時的時間，可以根據自己的表現取得授權。公民參與的重點是，讓政府內部意見與外部有溝通的橋樑。有衝突可以溝通，沒衝突的可以多一個意見來源。公民參與的前提是，公民參與的人可以 earn your credit，不是因為他是成員就當然有權力，而是他貢獻的程度。
 
舉例來說，新北青委會，我們每個人都要去學校演講，他們會去評估學生對我們意見的評估，會安排首長會談。
 
會去參訪公共政策，提出意見，我們的表現是也是評分的依據。
不是藝人一票平等的。實踐實質的參與，而不是投票。
我們會藉由我們的表現，讓內部評估我們能不能去合作。從他瞭解的程度，可以評估能不能跟他合作。
 
有分小組，私底下也會再開更小的會。實際上的事物也會找我們去介入。
 
 
我先回來論述一件事，代表社群還是代表個人。回過頭來我什麼時候可以說什麼樣的話，網路討論的意見對我的意見制約我到什麼程度，如果我不認同網路上討論的意見，我怎麼回應？
 
我的做法比較特別。我曾經跟家驊有一個討論，在意見審議上，你要馬是很強的專家，要馬是一個群體。他覺得我的狀況很特別，有當然是個專家，有些時候又是一個團體的代表。我那時候想說是不是要經營一個群體，變成有群體的專家，變成專業型的意見領袖。我幾乎是獨來獨往。大家發覺我常常在換工作，那時候我跟家華說，我比較想要做的是一個 powerful 的個人。因為我認為群體是由個人組成的，群體需要有各種個人意見，互相折衝。群體是由獨特性的個體組成的，不然會是信徒而已。個體夠多，組成複合性的群體。如果我去組織的群體，都是沒有主體性的，那我就被卡死了。一個群體應該是能夠迅速回應，每個人的意見都是可以自己表達。我不想組織群體。
 
我對每個人講的話都是具有公共性的。我都會承認，我不會否認。我知道個人是有極限的。群體組成的前提是，都有個人思考能力的。
 
現階段公民社會發展歷程，作為有專業能力的個體，讓其他人可以參考我的路線，去幫其他人排除障礙。有廠商駐點、代理人
 
我就建立一條路徑告訴你，我就打破你只能三四萬薪水的價值。這已經比過去的薪水好很多了。我現在處理的問題是，大學沒畢業的人如何任職正式職位。他們之前想要聘任我當機要卡關。這些障礙要怎麼去排除，要找我，要讓規則配合我。我成功了，我找到可以用大學沒畢業的資格去當機要的資格。
 
政府單位裡破窗是重要的，有了先例，政治上才有空間。後面有沒有人走得動，我不知道。從外部進來的角色，讓這群人進來，不可以每個進來的人都不賺錢。必須確定進來做十年不會被產業淘汰。要有 carreer path。如果不能回到民間，就是賭一輩子。
 
為什麼願意進來。熱血是不能當飯吃的。善意是不能成為公共事務的基礎。
